[build-system]
requires = ["hatchling"] 
build-backend = "hatchling.build"

[project]
name = "advmonitors"
version="1.0.0"
description = "Monitoring tools for the Advantics CAN interfaces"
requires-python = ">=3.9"
authors = [
  { name = "Axel Voitier", email = "axel.voitier@advantics.fr" },
  { name = "Can Berk Durmus", email = "can.durmus@advantics.fr" },
  { name = "Baptiste Pestourie", email = "baptiste.pestourie@advantics.fr" },
]

# Note: project-level dependencies are automatically installed in the default environement
# and all the envs inheriting from it
dependencies = [
  "python-can>=4.4.2",
  "cantools~=39.4.0",
  "typer~=0.12.0",
  "asciichartpy~=1.5.0",
]

[project.urls]
Homepage = "https://github.com/ADVANTICS/examples"

[tool.hatch.build.targets.wheel]
packages = ["advmonitors"]
include = [
  "advmonitors/conf/*.conf",
]

[project.scripts]
evse-monitor="advmonitors.evse:cli_main"
pev-monitor="advmonitors.pev:cli_main"


[tool.mypy]
namespace_packages = true
explicit_package_bases= true
ignore_missing_imports = true

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true
